### ISSUE TITLE
send交易无法发送成功

### ISSUE THREAD

**Issue by qtjiang** [Agzs/BlockMaze#9]
环境Ubuntu18.04，geth1.10 ，我尝试使用test的pow测试，mint交易可以成功被验证，send交易验证失败，报错信息：

Trying to generate send proof...
* G1 elements in proof: 2
* G2 elements in proof: 1
* Proof size in bits: 1019
* Proof size in bytes: 127.38
QAP divisibility check failed.
Verifying send proof unsuccessfully!!!
add txpool err Verifying send proof failed!!!
Error: Verifying send proof failed!!!
    at web3.js:3143:20
    at web3.js:6411:15
    at web3.js:5081:36
    at <anonymous>:1:1

QAP验证失败是不是说明零知识证明失效了，这部分的代码有问题？

**Comment by leoyzx** [comment]
你好，请问有联系方式吗？关于项目也有一些问题想咨询一下

**Comment by otaJiang** [comment]
> 你好，请问有联系方式吗？关于项目也有一些问题想咨询一下

你可以发我邮箱，jqt@mail.ustc.edu.cn

**Comment by Agzs** [comment]
你好，需要提供执行Mint和Send的相关参数哈，一般QAP失败说明产生proof的参数没有满足约束关系，后续有问题也可以邮箱联系我哈aguanzs@163.com
